### ISSUE TITLE
Issue with import Quaternions with Python 2.7, Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv

### ISSUE THREAD

**Issue by eva-yhuang** [moble/Quaternions#11]
Hi, 
After I run setup.py, and in python 2.7 run `import Quaternions`, I encountered
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Evalien/.local/lib/python2.7/site-packages/Quaternions/__init__.py", line 21, in <module>
    _Quaternions = swig_import_helper()
  File "/Users/Evalien/.local/lib/python2.7/site-packages/Quaternions/__init__.py", line 20, in swig_import_helper
    return importlib.import_module('_Quaternions')
  File "/Users/Evalien/miniconda3/envs/python2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dlopen(/Users/Evalien/.local/lib/python2.7/site-packages/_Quaternions.so, 2): Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/Evalien/.local/lib/python2.7/site-packages/_Quaternions.so
  Expected in: /usr/lib/libstdc++.6.0.9.dylib
```
 I am running Python 2.7 with swig version 3.0.10, Mac High Sierra. Any chance this error seems familiar? Thanks a ton in advance!

**Comment by moble** [comment]
The part that says the symbol `__ZNKSt5ctypeIcE13_M_widen_initEv` isn't found translates to a linking failure where the actual binary for `std::ctype<char>::_M_widen_init() const` is missing.  This is a standard result when you compile different parts of the executable with two different compilers, or maybe if your compiler includes headers from one place but gets its libraries from another.  These both sound plausible, because it looks like you're using two different python versions here.  In particular, the `Quaternions` package is being found in `/Users/Evalien/.local/lib/python2.7/site-packages/Quaternions`, but the python you're actually using is in `/Users/Evalien/miniconda3/envs/python2/lib/python2.7/`.  So you've screwed up the build part of this somehow.  My guess is that you didn't activate your `python2` conda env correctly before building, or maybe you have some weird PYTHONPATH environment variable, or something like that.  Run `env` to make sure you don't have any terrible python-related variables defined, then activate the conda env correctly, and build it all over.

**Comment by eva-yhuang** [comment]
Hi @moble ,
Thanks! I think `/Users/Evalien/.local/lib/python2.7/site-packages` comes from site.USER_SITE so I tried to build and install without the `--user` flag. Now I encounter same error message when run `import GWFrames`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "GWFrames/__init__.py", line 9, in <module>
    import Quaternions
  File "/Users/Evalien/miniconda3/envs/python2/lib/python2.7/site-packages/Quaternions/__init__.py", line 21, in <module>
    _Quaternions = swig_import_helper()
  File "/Users/Evalien/miniconda3/envs/python2/lib/python2.7/site-packages/Quaternions/__init__.py", line 20, in swig_import_helper
    return importlib.import_module('_Quaternions')
  File "/Users/Evalien/miniconda3/envs/python2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dlopen(/Users/Evalien/miniconda3/envs/python2/lib/python2.7/site-packages/_Quaternions.so, 2): Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/Evalien/miniconda3/envs/python2/lib/python2.7/site-packages/_Quaternions.so
  Expected in: /usr/lib/libstdc++.6.0.9.dylib
```
I don't think I have PYTHONPATH defined in my conda environment. Is there anything else you suggest checking? Thanks a lot!

**Comment by moble** [comment]
These sorts of things really imply that there's some inconsistency between how different parts of a code were compiled.  So I really recommend starting fresh and recompiling all in one go.  Maybe even delete your `~/.local/lib/python2.7` directory if you can, because that's a pretty old way of using python, and might screw up more modern approaches (like conda, pipenv, or virtualenv).  I've added a set of steps to [the GWFrames README](https://github.com/moble/GWFrames#quick-start) that should work.

If they don't, it's probably an issue with your installation of conda itself.  It does happen occasionally that changes in conda cause library snafus, and I know there have been lots of changes lately (including deprecation of libstdc++, which is mentioned in your error message).  In that case, the thing to do is to actually reinstall conda.

**Comment by eva-yhuang** [comment]
Hi, 
The README is very helpful, thank you! I reinstalled conda (because new environment alone still didn't work) and now it worked! Thank you being so patient and helpful! 😃

**Comment by moble** [comment]
Glad to hear it!
